apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-generator          # lowercase only, valid ArgoCD name
  namespace: argocd              # ArgoCD namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/preangelleo/video-generation-docker.git'  # public repo
    targetRevision: HEAD
    path: chart/video-generator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default           # where you want to deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
