apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-video
  labels:
    app: {{ .Release.Name }}-video
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-video
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
