apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-hub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:stable-alpine
          volumeMounts:
            - name: frontend-code
              mountPath: /usr/share/nginx/html
      volumes:
        - name: frontend-code
          hostPath:
            path: /home/<user>/video-hub/frontend
            type: Directory
