apiVersion: v1
kind: Service
metadata:
  name: video-hub-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
  type: ClusterIP
