apiVersion: v1
kind: Service
metadata:
  name: video-hub-frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
  type: ClusterIP
