replicaCount: 1

image:
  repository: betashow/video-generation-api   # public image, no login needed
  tag: latest

service:
  type: NodePort
  port: 5000           # container port
  nodePort: 31085      # NodePort accessible from browser/host

containerPort: 5000    # matches container port
